name: superapp_sdk

packages:
  - packages/**
  - examples/**


command:
  bootstrap:
    environment:
      sdk: ^3.6.2
      flutter: '>=3.3.0'
    dependencies:
      http: ^1.3.0
      path_provider: ^2.1.5
      encrypt: ^5.0.3
      app_links: ^6.4.0
      skit_sdk:
        path: packages/skit_sdk
    dev_dependencies:
      build_runner: ^2.3.3

scripts:
  lint:all:
    run: melos run analyze && melos run format
    description: "Run all static analysis and formatting checks"